### PR TITLE
remove `project_name` parameter

### PR DESCRIPTION
**Pull request by cjyetman**
In the `workflow.transition.monitor` use case, the `project_name` parameter is set in the `parameter_files/WebParameters_docker.yml` and/or `parameter_files/WebParameters_local.yml` files, but it is never used except for being passed as an argument to `create_interactive_report()` which also never uses the argument. Additionally, it is set by default to `"working_dir"` in both cases, which suggests that this is a long leftover option that is not being used as expected. `create_interactive_report()` sets a default value for its `project_name` argument (which is also set to `"working_dir"` by default), so removing that argument from the call in `web_tool_script_3.R` should not have any negative effect. I would suggest that once this PR is merged, that the `project_name` argument also be removed from `create_interactive_report()` in `pacta.portfolio.report`.

@AlexAxthelm @jacobvjk @Antoine-Lalechere I have a minor concern that `project_name` may be used/expected in some other workflows, and removing it here may cause some confusion as `workflow.transition.monitor` is usually considered the standard model for how PACTA *should* be run, but removing it here should not immediately break any other workflows as far as I can tell. Do you have nay concerns about this?

### CODE REVIEW

**Comment by jacobvjk** [comment]
which other workflows might be affected? MFM potentially? @AlexAxthelm @Antoine-Lalechere ? I'm not aware of any other ones

**Comment by jacobvjk** [comment]
just seeing that `workflow.ust.fio` uses this https://github.com/RMI-PACTA/azure-pacta-runner to run PACTA, so as long as we are certain that `project_name` is not needed there (it does not seem so), none of the projects I know about seem to use it

**Comment by cjyetman** [comment]
[workflow.meta.report.data.creator](https://github.com/RMI-PACTA/workflow.meta.report.data.creator) doesn't have any hits for `project_name`:
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.meta.report.data.creator%20project_name&type=code

**Comment by Antoine-Lalechere** [comment]
MFM and CA100 don't seem to use it neither

**Comment by cjyetman** [comment]
great! So this is just waiting to be approved then

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
