### PR TITLE
Update dependencies to include real estate

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Not to be merged until dependencies are resolved.

Updates build configuration to use latest version of testing RE files.

Depends On:
- [ ] https://github.com/RMI-PACTA/pacta.portfolio.report/pull/93
- [ ] https://github.com/RMI-PACTA/templates.transition.monitor/pull/34

### CODE REVIEW

**Comment by jdhoffa** [comment]
@AlexAxthelm just flagging that I don't expect this to work, since the `user_results` directory will need to include the new `real_estate` directory? Unless you already added those on Azure.

See https://github.com/RMI-PACTA/user_results/pull/24/commits/1cebba7eb90f6d00e38c8d3a46e5e7da6c611a32

**Comment by MonikaFu** [comment]
Are we using correct templates for German COP reports? I see a lot of 'CHAPTER TO BE REVIEWED FOR COP 2024' lines in there. Or do we still need a review of the German text? @jdhoffa maybe you are aware?

**Comment by MonikaFu** [comment]
The table with links to real estate looks good to me. The only question I have is why some lines have a portfolio ID and some don't?

**Comment by AlexAxthelm** [comment]
LInes with a portfolio ID are for individual portfolios. Those without are for the participant-level (combined) reports.

**Comment by MonikaFu** [comment]
thanks @AlexAxthelm . So apart from the templates question in German it looks good to me.

**Comment by jdhoffa** [comment]
@MonikaFu can you please actually approve the PR :-)

**Comment by jdhoffa** [comment]
I have followed up with Matthias regarding the DE content. 

Regarding the RE content itself, FPRE will write that and circulate it before the end of the week.

**Review by MonikaFu — DISMISSED** [review]

**Pull request merged**
