### PR TITLE
Enable peer and User results in test pipeline

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Attempt to resolve "missing" peer results by using a non-default user_id in portfolio parameters.

Diagnosed by @jdhoffa.

- [x] Depends on https://github.com/RMI-PACTA/pacta.executive.summary/pull/319

Additional changes in this PR:
* Extend timeout for testing job from 15 to 30 minutes

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
I'm starting to think that the issue may not be the user ID, but something to do with the peer group names. I'm noting that [this chart](https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/rmi_pacta_2023q4_pa2024ch-20240514T085123Z/EN/asset_manager/1/working_dir/50_Outputs/rmi_pacta_2023q4_pa2024ch/report/index.html#current-low-carbon-exposure-vs.-future-low-carbon-build-out) shows points correctly for `All Participants` but not for `asset_manager`.
Screenshot_2024-05-14_09 44 13
Screenshot_2024-05-14_09 45 39

Are we missing some string sanitizing step?
cc @cjyetman @jdhoffa @MonikaFu

**Comment by MonikaFu** [comment]
It has always worked correctly but I can look into the function to see what it requires.

**Comment by jdhoffa** [comment]
FYI @MonikaFu
I spoke to @AlexAxthelm this morning, and we determined it was an issue with string formatting in the CI/CD side. 
It should be `assetmanager` not `asset_manager`

Should be solved now.

**Comment by MonikaFu** [comment]
thanks for letting me know @jdhoffa!

**Comment by jdhoffa** [comment]
Hmm the check seems to now be failing because it can't pick up the appropriate .rds file:
Screenshot 2024-05-14 at 06 29 22


which is odd, because that file does seem to be in the Azure blob storage:
Screenshot 2024-05-14 at 06 29 06

**Comment by AlexAxthelm** [comment]
Sorted out the missing file issue (had forgotten that we sort results by project code). And no to new Errors! Now they're in the RMD file! Progress!

https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9082402131/job/24960195475#step:10:98

**Comment by AlexAxthelm** [comment]
@jdhoffa @MonikaFu It looks like the PNG files that the code is expecting now aren't what we have in our testing files:
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9082402131/job/24960194013#step:10:101

```
Quitting from lines 83-114 [survey_chapter] (./survey-chapter.Rmd)
Error in `pacta.executive.summary::readPNG()`:
! unable to open /user_results/PA2024CH/survey/EN/plot_layer_exclusion_coal.png
Backtrace:
 1. pacta.executive.summary::rasterGrob(...)
 2. pacta.executive.summary::readPNG(...)
Execution halted
```

And in the testing files we have:

plot_layer_asset_exclusion_coal_Corporate_bonds.png
plot_layer_asset_exclusion_coal_Listed_equities.png
plot_layer_asset_exclusion_oil_Corporate_bonds.png
plot_layer_asset_exclusion_oil_Listed_equities.png

**Comment by AlexAxthelm** [comment]
Found that I hadn't picked up the newest files. Uploaded to ABS and config updated in 
7b02c77

**Comment by AlexAxthelm** [comment]
@jdhoffa @MonikaFu It looks like peer comparison results are coming through nicely for the `bank` peer group, but none of the others (which is expected for the moment). If we generate some user results for the other peer groups, we should be able to get greens across the board.

**Comment by AlexAxthelm** [comment]
Link to Banks (EN) report: https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/rmi_pacta_2023q4_pa2024ch-20240514T210846Z/EN/bank/1/working_dir/50_Outputs/rmi_pacta_2023q4_pa2024ch/report/index.html

🎉  Executive Summary: https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/rmi_pacta_2023q4_pa2024ch-20240514T210846Z/EN/bank/1/working_dir/50_Outputs/rmi_pacta_2023q4_pa2024ch/executive_summary/template.pdf

**Comment by AlexAxthelm** [comment]
Dependcy PRs resolved. This is good to go upon approval.

**Review by jdhoffa — APPROVED** [review]

**Review by cjyetman — CHANGES_REQUESTED** [review]
As usual, these build scripts are bewildering, but on the surface the logic here seems to make sense. There are a number of checks failing though, is that expected?

**Comment by AlexAxthelm** [comment]
Hmm. the failing checks appear to be because the peers files for the score card were deleted in the latest version of that data. 

https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9099702553/job/25027104085?pr=312#step:10:106

For tracking that discussion: https://github.com/RMI-PACTA/user_results/pull/24#pullrequestreview-2060244237

**Comment by cjyetman** [comment]
should I set this as "ready for review" and approve then?

**Comment by AlexAxthelm** [comment]
> should I set this as "ready for review" and approve then?

@cjyetman I think it's better to get the correct file up on ABS before we merge, otherwise we'll get a bunch of red bubbles on `main`.

**Comment by jdhoffa** [comment]
I disabled FR and DE for a commit, but with https://github.com/RMI-PACTA/pacta.executive.summary/pull/323 merged, I think we can re-enable them again, since they should now generate without error

**Comment by AlexAxthelm** [comment]
Marking this as ready for review. The failing action is the "update comment" action, which is running into a known limit with GH comments (https://github.com/RMI-PACTA/actions/issues/74)

**Review by jdhoffa — APPROVED** [review]
hell yeah man!!

**Review by cjyetman — APPROVED** [review]

**Review by MonikaFu — COMMENTED** [review]
Looks reasonable although I can't entirely follow what it does. Will trust the others who approve.

**Pull request merged**
