### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by cjyetman**
This PR does all the appropriate things related to adding a license to the repo, including:
- adding a LICENSE file
- adding a LICENSE.md file
- properly specifying the license in the DESCRIPTION file

depends on #231

### CODE REVIEW

**Review by jdhoffa — CHANGES_REQUESTED** [review]
This PR does more than it claims

**Comment by cjyetman** [comment]
> This PR does more than it claims (e.g. it also adds a `DESCRIPTION` file)

sorry, should have said this depends (builds on) on #231 which adds the DESCRIPTION file

**Comment by jdhoffa** [comment]
But the LICENSE can be added on it's own, no?

**Comment by cjyetman** [comment]
> But the LICENSE can be added on it's own, no?

using {usethis} magic, it also adds a line to the DESCRIPTION file that specifies the license

**Comment by jdhoffa** [comment]
> > But the LICENSE can be added on it's own, no?
> 
> using {usethis} magic, it also adds a line to the DESCRIPTION file that specifies the license

Yup, `usethis` is really suited/ designed to be used in R packages so that makes sense

**Comment by jdhoffa** [comment]
> > Yup, `usethis` is only really suited/ designed to be used in R packages so that makes sense
> 
> true, but... if I'm going to use a DESCRIPTION file in this repo, I think it makes sense to specify the license in it

true... but, I think having a `LICENSE` file has value regardless of if you have a `DESCRIPTION` or not 😂

**Comment by cjyetman** [comment]
> true... but, I think having a `LICENSE` file has value regardless of if you have a `DESCRIPTION` or not 😂

which brings it back to the beginning... a built this PR on top of #231 which adds a DESCRIPTION, so given that as the head, if one were to add a LICENSE file it would follow that they should likely also edit the DESCRIPTION file, which is what I did here. Once #231 is merged and this PR is updated, you will see that there is only one line added to the DESCRIPTION file: `License: MIT + file LICENSE`

**Comment by jdhoffa** [comment]
What I'm getting at is:
In case we end up deciding on Thursday that `workflow.*` repos should not be packages, and we end up deciding NOT to merge #231, we may still want to add a `LICENSE` file here.

So a PR that just adds the `LICENSE` file alone still has value. It doesn't NEED to depend on a `DESCRIPTION` file...

**Comment by cjyetman** [comment]
> What I'm getting at is: In case we end up deciding on Thursday that `workflow.*` repos should not be packages, and we end up deciding NOT to merge #231, we may still want to add a `LICENSE` file here.
> 
> So a PR that just adds the `LICENSE` file alone still has value. It doesn't NEED to depend on a `DESCRIPTION` file...
> 
> and this PR (as it is currently named) I would expect to JUST add a `LICENSE` file. Especially given that no `DESCRIPTION` file currently exists on `main`.

Then let's just wait for the result of that meeting, as I already said I would do. If we decide that "workflow.*" maintainers are allowed to add a DESCRIPTION file then I will merge these PRs in order as intended. If not, I will close #231 and probably this one and possibly open a new PR that just adds a `LICENSE` and a `LICENSE.md` file.

This PR, as intended, was to "Add license", which in my mind includes adding a `LICENSE` file, plus adding a `LICENSE.md` file, plus, since it has/will have a DESCRIPTION file, adding the specification of the license to the DESCRIPTION file. To me there's no intent implicit in the title "Add license" that suggests that it can only add or modify a single file, the intent is to do all the things relevant to add a license to the repo, which in my mind, given a DESCRIPTION file, includes specifying the license appropriately in the DESCRIPTION file.

**Comment by cjyetman** [comment]
@jdhoffa does this make sense now?

**Review by jdhoffa — APPROVED** [review]
lgtm

**Pull request merged**
