### PR TITLE
feat: update executive summary to use GECO 2023 1.5C scenario

### PR DESCRIPTION
**Pull request by jdhoffa**
This is the scenario we assume will be used here.  I will leave this as a draft until this ticket:
https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10205#30820473 is decided and agreed upon.

Edit: I had to add an argument to `render_executive_summary` to parameterize the `scenario_source`, so this now depends on https://github.com/RMI-PACTA/pacta.executive.summary/pull/314

### CODE REVIEW

**Comment by cjyetman** [comment]
these probably need to be parameterized, no? maybe we can add a new, optional key in the project params?

**Comment by jdhoffa** [comment]
😂 yes probably

My goal with this PR was to get it working with minimal changes, but having it as a config key is definitely preferable

**Comment by cjyetman** [comment]
I guess no one's expecting the current code to be able to run any former COP project with an executive summary, so for now this shouldn't cause any problem.

**Review by cjyetman — APPROVED** [review]

**Review by AlexAxthelm — APPROVED** [review]
Agree that parameters would be better here, but that seems like an issue for `workflow.pacta` and friends

**Pull request merged**
