### PR TITLE
build(docker): Update references to use dev version of GENERAL report

### PR DESCRIPTION
**Pull request by AlexAxthelm**
**Not a real PR**

Updating the refs for `templates.transition.monitor`, so that we can run the build and test pipeline from this repo to see outputs from https://github.com/RMI-PACTA/templates.transition.monitor/pull/2

### CODE REVIEW

**Comment by cjyetman** [comment]
> @cjyetman it looks like the report is failing to build somewhere in `web_tool_script_3`. Any suggestions on how to diagnose?

Almost definitely in pacta.portfolio.report, and given the context, almost definitely related to the changes in the templates.

**Comment by cjyetman** [comment]
It's because of this https://github.com/RMI-PACTA/pacta.portfolio.report/pull/50
I'm looking into it.

**Comment by cjyetman** [comment]
added 2 commits to https://github.com/RMI-PACTA/templates.transition.monitor/pull/2
then started a re-run on the failing tests here

**Comment by cjyetman** [comment]
@AlexAxthelm is it possible that re-running only the failing tests did not force it to update to the latest commits on the `feature/text-updates` branch?

**Comment by cjyetman** [comment]
> @AlexAxthelm is it possible that re-running only the failing tests did not force it to update to the latest commits on the `feature/text-updates` branch?

testing that theory in https://github.com/RMI-PACTA/workflow.transition.monitor/pull/282

**Comment by cjyetman** [comment]
> > @AlexAxthelm is it possible that re-running only the failing tests did not force it to update to the latest commits on the `feature/text-updates` branch?
> 
> testing that theory in #282

theory confirmed, all test pass in #282

**Comment by cjyetman** [comment]
@AlexAxthelm next problem is: test results/reports for GENERAL 2023Q4 don't appear to have any data to display, but GENERAL 2022Q4 does

**Comment by AlexAxthelm** [comment]
> > > @AlexAxthelm is it possible that re-running only the failing tests did not force it to update to the latest commits on the `feature/text-updates` branch?
> > 
> > 
> > testing that theory in #282
> 
> theory confirmed, all test pass in #282

Confirmed in this branch too by creating a new git hash and pushing. 

Lesson learned: `actions/checkout` grabs the same SHA across re-runs (but I have noticed that updating an action across re-runs can yield different behavior)

**Pull request closed without merging**
