### PR TITLE
Add GHCR image to docker comment

### LINKED ISSUE #279: Add GHCR image to Docker comment output
For some reason, the `add-comment` action isn't picking up the artifact emitted during the `docker-build-push` action.

This means that as of now, there isn't a way to see which image was created with the GHCR action

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Closes #279

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
🎉

**Comment by AlexAxthelm** [comment]
@cjyetman what do you think? The only big change that I'm thinking about at this point is to split the "docker images" and "test reports" into separate comments, but I'll let you decide if that's something you think is important.

Otherwise I'm fine leaving this where it is.

**Comment by cjyetman** [comment]
> @cjyetman what do you think? The only big change that I'm thinking about at this point is to split the "docker images" and "test reports" into separate comments, but I'll let you decide if that's something you think is important.
> 
> Otherwise I'm fine leaving this where it is.

for me, this is good as it is now... potential future improvements are welcome

**Comment by cjyetman** [comment]
mildly concerned that the GENERAL 2023Q4 reports don't have any charts, e.g. https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/rmi_pacta_2023q4_general-20240312T133847Z/EN/other/1/working_dir/50_Outputs/rmi_pacta_2023q4_general/report/index.html

**Pull request merged**
