### PR TITLE
feat(app): #284 Add 2023Q4 Scenario sources

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Add 2023 Scenario sources to scenario source list for GENERAL parameters, allowing for GENERAL to build meaningful 2023Q4 reports

Closes: #284

### CODE REVIEW

**Comment by cjyetman** [comment]
The GENERAL 2023Q4 interactive report is clearly messed up in multiple ways though:
https://pactadatadev.blob.core.windows.net/ghactions-workflow-transition-monitor-results-reports/rmi_pacta_2023q4_general-20240320T123256Z/EN/other/1/working_dir/50_Outputs/rmi_pacta_2023q4_general/report/index.html#scope-and-parameters-of-the-analysis

**Comment by AlexAxthelm** [comment]
🤔 hmm. yeah. the volume trajectory charts are hjust sort of missing there, aren't they. I'm out of my depth in diagnosing that.

**Comment by cjyetman** [comment]
Let's see what #286 does, at least determine if it's related to the parameters being set or something else.

**Comment by cjyetman** [comment]
@AlexAxthelm I think it's become clear that this should be closed in favor of something like #287?

**Comment by cjyetman** [comment]
closing in favor of #287

**Pull request closed without merging**
