### PR TITLE
add data checks before creating a report and warn of problems

### PR DESCRIPTION
**Pull request by cjyetman**
- [x] depends on #297

### CODE REVIEW

**Comment by jdhoffa** [comment]
PR looks fine, but the Dockerfile is failing to build... Likely unrelated to this. 

But I would prefer to wait until checks pass before merging.

**Comment by cjyetman** [comment]
It (anything) needs #297 to work. I merged the changes from it here to test and the tests passed, then removed them again to avoid merge conflicts.

**Comment by jdhoffa** [comment]
Sounds good!
Then let's say depends on #297

**Review by jdhoffa — APPROVED** [review]
lgtm!

**Pull request merged**
