### PR TITLE
VM storage hack

### PR DESCRIPTION
**Pull request by jdhoffa**
I don't think we should necessarily merge this. This is just a hack that is required to get the docker stuff working on the VM (with limited storage).

Just want to keep track of what we had to do to make it work.

### CODE REVIEW

**Comment by jdhoffa** [comment]
Note-to-self:
Revisit this ASAP lol

**Comment by AlexAxthelm** [comment]
@jdhoffa my inclination would be to close this branch, and focus on automated builds, rather than building on a machine that we intend to shutdown soon.

**Comment by jdhoffa** [comment]
I back that. But maybe, for safety, we leave it open until we have successfully done one fully automated build?

**Comment by AlexAxthelm** [comment]
@jdhoffa @cjyetman, I've been able to successfully build a few docker images and push to registry without this branch involved. Move to close?

**Comment by cjyetman** [comment]
I'm in favor of closing, though I never used/needed this branch... I think @jdhoffa used it.

**Comment by jdhoffa** [comment]
Yayyyy I'm so happy to close this haha

**Pull request closed without merging**
