### PR TITLE
use a single Docker build action and other actions to trigger in diff…

### PR DESCRIPTION
**Pull request by cjyetman**
…erent contexts

supersedes #200

### CODE REVIEW

**Review by jdhoffa — DISMISSED** [review]
lgtm!!

**Comment by cjyetman** [comment]
@jdhoffa I had to fix the SHA in the comment because it was using some temporary SHA for a pseudo merge commit I think... now it reports the proper SHA for the commit that triggered it 
Screenshot 2023-07-07 at 15 27 24

**Comment by cjyetman** [comment]
and now I fixed it so that the PACTA-bot comment is updated instead of a new comment every time the workflow is run

**Review by jdhoffa — APPROVED** [review]
very cool, and still lgtm!

**Pull request merged**
