### PR TITLE
Use new comment action with history

### PR DESCRIPTION
**Pull request by AlexAxthelm**
- [x] Depends on https://github.com/RMI-PACTA/actions/pull/62
- [x] Depends on https://github.com/RMI-PACTA/actions/pull/63

Adds code to export information about build and testing status to use comment action from RMI-PACTA/actions repo

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]

**Review by cjyetman — CHANGES_REQUESTED** [review]
does this completely remove the comment that adds a link to the GHCR (public) image?

**Comment by AlexAxthelm** [comment]
> does this completely remove the comment that adds a link to the GHCR (public) image?

For some reason this isn't including that in the table output. I'm still trying to diagnose that.

**Comment by AlexAxthelm** [comment]
#279 is opened to track that.

**Review by cjyetman — APPROVED** [review]
#279 is a priority for me because I use it heavily for testing and this is a regression

**Pull request merged**
